name: browser_html_bookmarks_to_json
description: Convert Browser HTML exported Bookmarks to JSON format. Works with MS Edge, Firefox and Chrome.
version: 1.0.0
repository: https://github.com/feliperfdev/browser_html_bookmarks_to_json

environment:
  sdk: ^3.8.0

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
